name: Send To Linode
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build Dotnet Core App
        run: dotnet publish -c Release --no-restore
      - name: Move Systemd service
        run: mv ./scripts/* ./MoistBot/bin/Release/netcoreapp3.1/publish/
      - name: Update Json Secrets
        uses: microsoft/variable-substitution@v1
        with:
          files: './MoistBot/bin/Release/netcoreapp3.1/publish/appsettings.Production.json'
        env:
          TwitchSettings.ClientId: ${{ secrets.TWITCH_CLIENT_ID }}
          TwitchSettings.ClientSecret: ${{ secrets.TWITCH_CLIENT_SECRET }}
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Build Vuejs App
        working-directory: ./MoistBot/client
        run: |
          npm install
          npm run build
      - name: Attach Vuejs App
        run: |
          rm -rf ./MoistBot/bin/Release/netcoreapp3.1/publish/client/*
          mkdir ./MoistBot/bin/Release/netcoreapp3.1/publish/client/dist
          mv ./MoistBot/client/dist/* ./MoistBot/bin/Release/netcoreapp3.1/publish/client/dist
      - name: Push To Linode
        run: |
          mkdir ~/.ssh
          echo "$my_ssh_key" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
          rsync -avz -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ./MoistBot/bin/Release/netcoreapp3.1/publish/* gh_actions@178.79.157.25:/var/app
        env:
          my_ssh_key: ${{ secrets.LINODE_UPLOAD }}
